curl -X POST -H "Content-Type: text/plain" "http://localhost:8080/app/user?age=71&firstname=Johny&lastname=Aloha"
curl -X POST -H "Content-Type: text/plain" "http://localhost:8080/app/user?age=35&firstname=Jack&lastname=Smith"
curl -X POST -H "Content-Type: text/plain" "http://localhost:8080/app/user?age=32&firstname=Fernando&lastname=Rodriguez"
curl -X POST -H "Content-Type: text/plain" "http://localhost:8080/app/user?age=38&firstname=Lorelay&lastname=Camus"
curl -X POST -H "Content-Type: text/plain" "http://localhost:8080/app/user?age=73&firstname=Norbert&lastname=Presley"
curl -X POST -H "Content-Type: text/plain" "http://localhost:8080/app/user?age=54&firstname=Jennifer&lastname=Artist"
